---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: ab16093d81c522a3ba6bdd1745e0d3b7f18c6065
  labels:
    app.kubernetes.io/name: consumer
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: consumer
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: ab16093d81c522a3ba6bdd1745e0d3b7f18c6065
      labels:
        app.kubernetes.io/name: consumer
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: sayed/consumer:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            successThreshold: 1
          name: consumer
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
